Fix a memory leak in hazelcast LeaderInitiator
spring-projects/spring-integration-extensions pull request #236
Opened 2020-10-15 08:16 UTC by mleguevel

According to the hazelcast team: "The logic assumes that locks are generally acquired & released in a fairly short time or hold a very long time without unlocking. But in this case, is a bit different, it holds the lock for a long time but also does lock/unlock very frequently". The previous implementation used the described logic, first acquiring a lock and then doing frequent tryLock/unlock. Doing this leads to com.hazelcast.cp.internal.datastructures.lock.Lock#ownerInvocationRefUids to grow without ever being cleaned thus leading to an OutOfMemory error eventually.

2020-10-15 08:16 UTC, pivotal-issuemaster commented
@mleguevel Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-integration-extensions&pullRequestId=236)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-integration-extensions&pullRequestId=236) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

2020-10-15 08:17 UTC, pivotal-issuemaster commented
@mleguevel Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-integration-extensions&pullRequestId=236)!

2020-10-15 17:24 UTC, artembilan commented
Hi, @mleguevel !

Would you mind to explain the fix another way, so it is easy to understand what is going on?
And why have you changed the test?
Don't we need to hon or that Raft algorithm any more?

Thanks

2020-10-19 07:25 UTC, mleguevel commented
Hello @artembilan,

**About the fix:**
Currently, hazelcast has a bug when doing an initial `tryLock` on the FencedLock and then doing a lot of `tryLock`/`unlock`. In other words, we can't hold a lock for a long time while also calling `tryLock` and `unlock` frequently on it. This bug causes an internal map to grow indefinitely and thus leading to an OOM. [They have acknowledged](https://github.com/hazelcast/hazelcast/issues/17709#issuecomment-709370454) that it isn't a normal behavior but they don't expect to fix it before version 4.2 (the current version being 4.0.3).
The idea behind this fix is to stop doing the frequent `tryLock` / `unlock`. As I said in the [bug report](https://github.com/spring-projects/spring-integration-extensions/issues/235#issuecomment-708983702), I'm not sure that the algorithm is totally equivalent. I'm not sure about the "else" of the original algorithm in particular:

```java
else {
	this.locked = false;
	// We were not able to acquire it, therefore not leading any more
	handleRevoked();
	if (isRunning()) {
		// Try again quickly in case the lock holder dropped it
		Thread.sleep(LeaderInitiator.this.busyWaitMillis);
	}
}
```
Because I don't know in which case this is invoked. I was hoping you could help me improve the fix if you think that it's not equivalent :)

**About the modifications in the test:**
As I said in the [bug report](https://github.com/spring-projects/spring-integration-extensions/issues/235#issuecomment-708983702), I assumed that you initialized 3 HazelcastInstance in the tests to circumvent the fact that hazelcast 3.12.x does not start in unsafe mode with less than 3 nodes. If my assumptions are not correct, I can set the other 2 instances back.

2020-10-19 15:44 UTC, artembilan requested changes
So, I'm merging this with some minor code clean up and adding your name to the author list.

👍

2020-10-19 15:44 UTC, artembilan commented on spring-integration-hazelcast/src/test/java/org/springframework/integration/hazelcast/leader/LeaderInitiatorTests.java
> +			config.getCPSubsystemConfig().setCPMemberCount(0)
Yes, you are right: with HZ-3.12 it "does not start in unsafe mode with less than 3 nodes".
So, this CP Member `0` is something new in HZ 4.0.
Thank you for sharing that and probably it's is good to revise all the tests to work in that unsafe mode when we really don't need a distributed consensus to satisfy 😄

2020-10-19 15:44 UTC, artembilan commented on spring-integration-hazelcast/src/main/java/org/springframework/integration/hazelcast/leader/LeaderInitiator.java
> +						if (LeaderInitiator.this.lock.isLocked()) {
I think this `isLocked()` does the trick for us.
We probably indeed should not re-lock from now on and fully rely on the CP subsystem in HZ.

2020-10-19 16:09 UTC, artembilan commented
Merged as https://github.com/spring-projects/spring-integration-extensions/commit/b568662cdbd78f6cda084995a2cf0fd7478971ff.

@mleguevel , thank you for contribution; looking forward for more!

2020-10-19 16:09 UTC, closed without merging